version: 2.1

executors:
  common-executor:
    working_directory: /go/src/github.com/Clever/timestamper
    docker:
    - image: circleci/golang:1.13-stretch
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      GOPRIVATE: github.com/Clever/*
  deploy-executor:
    docker:
    - image: cimg/base:2020.01
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      GOPRIVATE: github.com/Clever/*

commands:
  clone-ci-scripts:
    description: Clone the ci-scripts repo
    steps:
    - run:
        command: cd .. && git clone --depth 1 -v https://github.com/Clever/ci-scripts.git && cd ci-scripts && git show --oneline -s
        name: Clone ci-scripts

jobs:
  build-publish:
    executor: common-executor
    steps:
    - checkout
    - run: make install_deps
    - run: make build
    - clone-ci-scripts
    - setup_remote_docker
    - run: ../ci-scripts/circleci/catapult-publish-lambda $APP_NAME

  unit-test:
    executor: common-executor
    steps:
    - checkout
    - run: make install_deps
    - run: make build
    - run:
        command: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
        name: Set up CircleCI artifacts directories
    - run:
        command: git config --global "url.ssh://git@github.com/Clever".insteadOf "https://github.com/Clever"
    - run:
        name: Add github.com to known hosts
        command: mkdir -p ~/.ssh && touch ~/.ssh/known_hosts && echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
    - run: make test

  deploy:
    executor: deploy-executor
    steps:
    - clone-ci-scripts
    - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then ../ci-scripts/circleci/dapple-deploy $DAPPLE_URL $DAPPLE_USER $DAPPLE_PASS $APP_NAME clever-dev no-confirm-deploy; fi;
    - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then ../ci-scripts/circleci/dapple-deploy $DAPPLE_URL $DAPPLE_USER $DAPPLE_PASS $APP_NAME production no-confirm-deploy; fi;

workflows:
  version: 2.1
  build_test_publish_deploy:
    jobs:
    - build-publish
    - unit-test
    - deploy:
        requires:
        - build-publish
        - unit-test
